src/src/Entity/Mandat.php
<?php

namespace App\Entity;

use App\Repository\MandatRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MandatRepository::class)
 */
class Mandat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Client::class, inversedBy="mandat", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    public $client;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="mandats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $broker;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    public $document;

    /**
     * @ORM\OneToOne(targetEntity=Resiliation::class, inversedBy="mandat")
     */
    private $resiliation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_signed;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getBroker(): ?User
    {
        return $this->broker;
    }

    public function setBroker(?User $broker): self
    {
        $this->broker = $broker;

        return $this;
    }

    public function getDocument(): ?string
    {
        return $this->document;
    }

    public function setDocument(string $document): self
    {
        $this->document = $document;

        return $this;
    }

    public function getResiliation(): ?Resiliation
    {
        return $this->resiliation;
    }

    public function setResiliation(?Resiliation $resiliation): self
    {
        $this->resiliation = $resiliation;

        return $this;
    }

    public function getIsSigned(): ?bool
    {
        return $this->is_signed;
    }

    public function setIsSigned(bool $is_signed): self
    {
        $this->is_signed = $is_signed;

        return $this;
    }
}

src/src/Form/MandatType.php
<?php

namespace App\Form;

use App\Entity\Mandat;
use App\Form\ClientType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MandatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('client', ClientType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Mandat::class,
        ]);
    }
}

src/src/Controller/MandatController.php
<?php

namespace App\Controller;

use App\Entity\Mandat;
use App\Form\MandatType;
use App\Repository\MandatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

/**
 * @Route("/mandat")
 * @isGranted("IS_AUTHENTICATED_FULLY")
 */
class MandatController extends AbstractController
{
    /**
     * @Route("/", name="mandat_index", methods={"GET"})
     */
    public function index(MandatRepository $mandatRepository): Response
    {
        return $this->render('mandat/index.html.twig', [
            'mandats' => $mandatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="mandat_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $mandat = new Mandat();
        $form = $this->createForm(MandatType::class, $mandat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $mandat->setCreationDate(new \DateTime());
            $mandat->setIsSigned(false);
            $entityManager->persist($mandat);
            $entityManager->flush();

            return $this->redirectToRoute('mandat_index');
        }

        return $this->render('mandat/new.html.twig', [
            'mandat' => $mandat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="mandat_show", methods={"GET"})
     */
    public function show(Mandat $mandat): Response
    {
        return $this->render('mandat/show.html.twig', [
            'mandat' => $mandat,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="mandat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Mandat $mandat): Response
    {
        $form = $this->createForm(MandatType::class, $mandat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('mandat_index');
        }

        return $this->render('mandat/edit.html.twig', [
            'mandat' => $mandat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="mandat_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Mandat $mandat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$mandat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($mandat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('mandat_index');
    }

    /**
     * @Route("/download/{filename}", name="mandat_download", methods={"GET"})
     */
    public function downloadAction(KernelInterface $kernel, $filename)
    {
        
        $path = $kernel->getProjectDir() . '/var/pdf/';
        $content = file_get_contents($path.$filename);

        $response = new Response();

        //set headers
        $response->headers->set('Content-Type', 'mime/type');
        $response->headers->set('Content-Disposition', 'attachment;filename="'.$filename);

        $response->setContent($content);
        return $response;
    }

    /**
     * @Route("/open/{filename}", name="mandat_open", methods={"GET"})
     */
    public function openAction(KernelInterface $kernel, $filename)
    {
        $path = $kernel->getProjectDir().'/var/pdf/'.$filename;

        return new BinaryFileResponse($path);
    }

}

src/templates/mandat/_delete_form.html.twig
<form method="post" action="{{ path('mandat_delete', {'id': mandat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mandat.id) }}">
    <button class="btn btn-danger"><i class="fas fa-trash"></i> Supprimer</button>
</form>

src/templates/mandat/_form.html.twig
<div class="user container">
{{ form_start(form) }}
  <div class="form-group">
    {{ form_row(form.document, { 'attr': {'class': 'form-control form-control-user'} } ) }}
    {{ form_row(form.client, { 'attr': {'class': 'form-control form-control-user'} } ) }}
    {{ form_row(form.broker, { 'attr': {'class': 'form-control form-control-user'} } ) }}
  </div>
    <button type="submit" class="btn btn-primary btn-user btn-block">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}
</div>

src/templates/mandat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer le Mandat{% endblock %}

{% block body %}
    <h1>Editer le Mandat</h1>

    {{ include('mandat/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a class="btn btn-primary btn-user" href="{{ path('mandat_index') }}"> &#8592; Retour à la liste des mandats</a>

    {{ include('mandat/_delete_form.html.twig') }}
{% endblock %}

src/templates/mandat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des mandats{% endblock %}

{% block body %}
    <h1>Liste des mandats</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date de création</th>
                <th>Pdf</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for mandat in mandats %}
            <tr>
                <td>{{ mandat.id }}</td>
                <td>{{ mandat.creationDate ? mandat.creationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td><a href="{{ path('mandat_download', {'filename': mandat.document}) }}"><i class="fas fa-file-contract"></i></a></td>
                <td>
                    <a href="{{ path('mandat_show', {'id': mandat.id}) }}">show</a>
                    <a href="{{ path('mandat_edit', {'id': mandat.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucun mandat existant</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('mandat_new') }}">Ajouter</a>
{% endblock %}

src/templates/mandat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un Mandat{% endblock %}

{% block body %}
    <h1>Créer un Mandat</h1>

    {{ include('mandat/_form.html.twig') }}
    <br>
    <a class="btn btn-primary btn-user" href="{{ path('mandat_index') }}"> &#8592; Retour à la liste des mandats</a>
{% endblock %}

src/templates/mandat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mandat{% endblock %}

{% block body %}
    <h1>Mandat</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mandat.id }}</td>
            </tr>
            <tr>
                <th>Date de création</th>
                <td>{{ mandat.creationDate ? mandat.creationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Pdf</th>
                <td>{{ mandat.document }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary btn-user" href="{{ path('mandat_index') }}"> &#8592; Retour à la liste des mandats</a>

    <a class="btn btn-success" href="{{ path('client_edit', {'id': mandat.id}) }}">Editer</a>

    {{ include('mandat/_delete_form.html.twig') }}
{% endblock %}